services:
  auto-commit:
    networks:
      - default_network
    hostname: auto-commit
    container_name: auto-commit
    image: auto-commit:master
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - MONITOR_HOST=${MONITOR_HOST}
      - MONITOR_UPDATE=${MONITOR_UPDATE}
      - MONITOR_URL=${MONITOR_URL}
      - MONITOR_SECRET=${MONITOR_SECRET}
      - MONITOR_SRC=pipeline.codetreats.auto-commit
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_TO=${MAIL_TO}
      - LLM_URL=${LLM_URL}
      - LLM_MODEL=${LLM_MODEL}      
      - LLM_KEY=${LLM_KEY}
      - LLM_THROTTLING_TIME=${LLM_THROTTLING_TIME}
      - GIT_USER=${GIT_USER}
      - GIT_MAIL=${GIT_MAIL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - HOST_URL=https://${HOST_HOSTNAME}:${PORT_CODETREATS_AUTOCOMMIT_HTTP}
      - TZ=Europe/Berlin
      - JOB_TITLE=Auto-Commit
    ports:
      - ${PORT_CODETREATS_AUTOCOMMIT_HTTP}:443
      - ${PORT_CODETREATS_AUTOCOMMIT_KTOR}:8443
    volumes:
      - /media/nas/docker/common/apache:/apache:ro
      - /home/docker/tmp/gradle/auto-commit:/root/.gradle      
      - /media/nas/docker/data/auto-commit/diffs:/var/www/html/diffs
      - /media/nas/server/data/git:/git
      - /media/nas/server/data/git/codetreats/auto-commit/container/src/src:/debug/src/src:ro
      - /media/nas/server/data/git/codetreats/auto-commit/container/src/build.gradle.kts:/debug/src/build.gradle.kts:ro
      - /media/nas/server/data/git/codetreats/auto-commit/container/src/settings.gradle.kts:/debug/src/settings.gradle.kts:ro
  
    restart: always
networks:
  default_network:
    name: default_network
    external: true
